# Generated by Django 5.1.5 on 2025-01-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_category',
        ),
    ]
